services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && cd portfolio && python manage.py collectstatic --noinput
    startCommand: cd portfolio && python manage.py migrate --noinput && gunicorn portfolio.wsgi
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

databases:
  - name: portfolio-db
    plan: free


